-- LucidDreamer Knowledge Base — D1 Schema
-- Generated by d1_sync.py

-- ─── Ideas Table ─────────────────────────────────────────────────
-- The atomic unit: a single insight, question, risk, vision, etc.
CREATE TABLE IF NOT EXISTS ideas (
    id              TEXT PRIMARY KEY,
    title           TEXT NOT NULL,
    content         TEXT,
    idea_type       TEXT NOT NULL DEFAULT 'insight',
    source_model    TEXT,
    source_session  TEXT,
    source_file     TEXT,
    lineage         TEXT,  -- JSON array of parent idea IDs
    status          TEXT NOT NULL DEFAULT 'seed',
    tags            TEXT,  -- JSON array of string tags
    connections     TEXT,  -- JSON array of connection objects
    timestamp       REAL,
    metadata        TEXT   -- JSON object for extensible properties
);

-- ─── Relationships Table ─────────────────────────────────────────────────
-- Typed edges between ideas: evolves_from, contradicts, supports, etc.
CREATE TABLE IF NOT EXISTS relationships (
    source_id       TEXT NOT NULL,
    target_id       TEXT NOT NULL,
    relationship    TEXT NOT NULL,
    note            TEXT,
    strength        REAL DEFAULT 1.0,
    PRIMARY KEY (source_id, target_id, relationship),
    FOREIGN KEY (source_id) REFERENCES ideas(id),
    FOREIGN KEY (target_id) REFERENCES ideas(id)
);

-- ─── Sessions Table ──────────────────────────────────────────────────────
-- Research sessions, Tap sessions, creative sessions that produced ideas.
CREATE TABLE IF NOT EXISTS sessions (
    id              TEXT PRIMARY KEY,
    title           TEXT,
    date            TEXT,
    source_file     TEXT,
    session_type    TEXT,
    participants    TEXT,  -- JSON array of model IDs/names
    description     TEXT,
    ideas_produced  TEXT,  -- JSON array of idea IDs
    timestamp       REAL
);

-- ─── Models Table ────────────────────────────────────────────────────────
-- AI models that contributed ideas. Each has a personality and perspective.
CREATE TABLE IF NOT EXISTS models (
    id                  TEXT PRIMARY KEY,
    name                TEXT,
    alias               TEXT,
    personality         TEXT,
    strengths           TEXT,  -- JSON array
    perspective         TEXT,
    sessions_contributed TEXT, -- JSON array of session IDs
    ideas_contributed   TEXT   -- JSON array of idea IDs
);

-- ─── Indexes ─────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_ideas_type    ON ideas(idea_type);
CREATE INDEX IF NOT EXISTS idx_ideas_model   ON ideas(source_model);
CREATE INDEX IF NOT EXISTS idx_ideas_status  ON ideas(status);
CREATE INDEX IF NOT EXISTS idx_ideas_session ON ideas(source_session);
CREATE INDEX IF NOT EXISTS idx_rel_source    ON relationships(source_id);
CREATE INDEX IF NOT EXISTS idx_rel_target    ON relationships(target_id);
CREATE INDEX IF NOT EXISTS idx_rel_type      ON relationships(relationship);
CREATE INDEX IF NOT EXISTS idx_sessions_type ON sessions(session_type);
