"""
LIVING SCHEMA — The schema is alive.

Each agent interaction carries a MusicalSignature — its own tempo, key, intensity.
Each tile has a PersonalityWrap — alignment, risk tolerance, creativity, confidence.
When a tile is minted, the signature is generated FROM the personality.
The sonic shape engine can query the signature for real-time music generation.

This extends the conductor's tile/session schema with musical DNA.
The schema IS the sheet music.

Hermes Track 1: The Living Schema
"""

from __future__ import annotations

import hashlib
import math
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


# ─── Alignment Axis ──────────────────────────────────────────────────────────

class Alignment(Enum):
    """
    The personality axis: safety ↔ creative.
    Determines the fundamental tonal character.

    SAFE       → major key, consonant, resolved — reliable, steady
    BALANCED   → modal, suspended — adaptable, versatile
    CREATIVE   → minor, blues, chromatic — exploratory, edgy
    WILD       → chromatic, atonal, dissonant — unpredictable, boundary-pushing
    """
    SAFE = "safe"           # 0.0 - 0.25
    BALANCED = "balanced"   # 0.25 - 0.60
    CREATIVE = "creative"   # 0.60 - 0.85
    WILD = "wild"           # 0.85 - 1.0

    @classmethod
    def from_score(cls, score: float) -> "Alignment":
        """Map a 0.0–1.0 creativity/creativity_score to an alignment."""
        score = max(0.0, min(1.0, score))
        if score < 0.25:
            return cls.SAFE
        elif score < 0.60:
            return cls.BALANCED
        elif score < 0.85:
            return cls.CREATIVE
        else:
            return cls.WILD


# ─── Musical Signature ───────────────────────────────────────────────────────

@dataclass
class MusicalSignature:
    """
    The musical DNA of a tile.

    Every interaction carries this signature. The sonic shape engine reads it
    to generate real-time music. It's not metadata — it IS the music.

    Fields map directly to sonic-shape/harmonic_dictionary.py parameters,
    but are derived from personality, not from confidence bands alone.
    """
    # Tonality
    key: str                # e.g., "C minor", "F# major", "Bb chromatic"
    mode: str               # "major", "minor", "dorian", "blues", "chromatic", "whole_tone"
    root_note: str          # "C", "F#", "Bb"

    # Rhythm
    tempo_bpm: int          # 40–180
    time_signature: str     # "4/4", "3/4", "5/4", "6/8", "7/8"
    swing: float            # 0.0 (straight) to 1.0 (full swing)

    # Harmony
    harmonic_tension: float     # 0.0 (fully resolved) to 1.0 (maximum tension)
    dissonance: float           # 0.0 (consonant) to 1.0 (very dissonant)
    chord_quality: str          # "triad", "maj7", "dominant7", "minor9", "chromatic"

    # Expression
    intensity: float            # 0.0 (whisper) to 1.0 (fortissimo)
    dynamics: str               # "pp", "p", "mp", "mf", "f", "ff"
    articulation: str           # "legato", "staccato", "mixed", "blue"

    # Metadata
    born_from: str = ""         # what generated this signature
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        """Serialize to dictionary for JSON transport."""
        return {
            "key": self.key,
            "mode": self.mode,
            "root_note": self.root_note,
            "tempo_bpm": self.tempo_bpm,
            "time_signature": self.time_signature,
            "swing": round(self.swing, 3),
            "harmonic_tension": round(self.harmonic_tension, 3),
            "dissonance": round(self.dissonance, 3),
            "chord_quality": self.chord_quality,
            "intensity": round(self.intensity, 3),
            "dynamics": self.dynamics,
            "articulation": self.articulation,
            "born_from": self.born_from,
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "MusicalSignature":
        """Deserialize from dictionary."""
        return cls(**data)

    def summary(self) -> str:
        """One-line human-readable description."""
        return (
            f"{self.key} · {self.tempo_bpm} BPM · "
            f"tension={self.harmonic_tension:.2f} · "
            f"intensity={self.intensity:.2f} · "
            f"{self.dynamics} {self.articulation}"
        )


# ─── Personality Wrap ────────────────────────────────────────────────────────

@dataclass
class PersonalityWrap:
    """
    The personality that lives inside a tile.

    This wrap travels with every interaction. It shapes the musical signature,
    colors the voice, and tells the sonic engine how to feel.

    Generated by personality_encoder.py from model behavior, or set manually.
    """
    # Core traits (0.0–1.0)
    alignment: Alignment = Alignment.BALANCED
    risk_tolerance: float = 0.5          # cautious ↔ bold
    creativity_score: float = 0.5        # conventional ↔ innovative
    confidence_at_birth: float = 0.5     # how sure the model was when generating
    verbosity: float = 0.5               # terse ↔ expansive
    vocabulary_richness: float = 0.5     # simple ↔ rich
    emotional_range: float = 0.5         # stoic ↔ expressive

    # Behavioral patterns
    avg_response_length: int = 200       # characters
    tendency_to_question: float = 0.3    # 0.0 (never asks) → 1.0 (always questioning)
    tendency_to_hedge: float = 0.3       # 0.0 (direct) → 1.0 (hedges constantly)

    # Metadata
    model_name: str = ""
    born_at: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        """Serialize to dictionary."""
        return {
            "alignment": self.alignment.value,
            "risk_tolerance": round(self.risk_tolerance, 3),
            "creativity_score": round(self.creativity_score, 3),
            "confidence_at_birth": round(self.confidence_at_birth, 3),
            "verbosity": round(self.verbosity, 3),
            "vocabulary_richness": round(self.vocabulary_richness, 3),
            "emotional_range": round(self.emotional_range, 3),
            "avg_response_length": self.avg_response_length,
            "tendency_to_question": round(self.tendency_to_question, 3),
            "tendency_to_hedge": round(self.tendency_to_hedge, 3),
            "model_name": self.model_name,
            "born_at": self.born_at,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "PersonalityWrap":
        """Deserialize from dictionary."""
        d = dict(data)
        if "alignment" in d and isinstance(d["alignment"], str):
            d["alignment"] = Alignment(d["alignment"])
        return cls(**d)

    def summary(self) -> str:
        """One-line personality description."""
        return (
            f"[{self.alignment.value}] "
            f"risk={self.risk_tolerance:.2f} "
            f"create={self.creativity_score:.2f} "
            f"conf={self.confidence_at_birth:.2f} "
            f"verb={self.verbosity:.2f}"
        )


# ─── Living Tile ─────────────────────────────────────────────────────────────

@dataclass
class LivingTile:
    """
    A tile in LucidDreamer.AI that carries its own musical signature
    and personality wrap.

    Each tile is a snapshot of an agent interaction — a moment frozen in
    music. When the sonic shape engine processes the session, it reads
    each tile's signature to know what to play.

    The tile is minted (born) when an agent responds. Its personality
    determines its music. Its music IS its personality.
    """
    tile_id: str
    agent_name: str
    content: str                       # the actual text/response
    personality: PersonalityWrap       # who the agent was being
    signature: MusicalSignature        # the music inside
    parent_tile_id: Optional[str] = None  # for conversational threads
    created_at: float = field(default_factory=time.time)

    # Session context
    session_id: str = ""
    turn_index: int = 0

    @classmethod
    def mint(
        cls,
        agent_name: str,
        content: str,
        personality: PersonalityWrap,
        session_id: str = "",
        turn_index: int = 0,
        parent_tile_id: Optional[str] = None,
    ) -> "LivingTile":
        """
        Mint a new tile. The musical signature is generated from the personality.
        This is the birth of a tile — its personality becomes music.
        """
        tile_id = str(uuid.uuid4())
        signature = generate_signature_from_personality(personality, seed=tile_id)

        return cls(
            tile_id=tile_id,
            agent_name=agent_name,
            content=content,
            personality=personality,
            signature=signature,
            parent_tile_id=parent_tile_id,
            session_id=session_id,
            turn_index=turn_index,
        )

    def to_dict(self) -> dict:
        """Full serialization."""
        return {
            "tile_id": self.tile_id,
            "agent_name": self.agent_name,
            "content": self.content,
            "personality": self.personality.to_dict(),
            "signature": self.signature.to_dict(),
            "parent_tile_id": self.parent_tile_id,
            "created_at": self.created_at,
            "session_id": self.session_id,
            "turn_index": self.turn_index,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "LivingTile":
        """Deserialize."""
        return cls(
            tile_id=data["tile_id"],
            agent_name=data["agent_name"],
            content=data["content"],
            personality=PersonalityWrap.from_dict(data["personality"]),
            signature=MusicalSignature.from_dict(data["signature"]),
            parent_tile_id=data.get("parent_tile_id"),
            created_at=data.get("created_at", time.time()),
            session_id=data.get("session_id", ""),
            turn_index=data.get("turn_index", 0),
        )

    def summary(self) -> str:
        """Human-readable tile summary."""
        return (
            f"LivingTile [{self.tile_id[:8]}] "
            f"agent={self.agent_name} "
            f"turn={self.turn_index}\n"
            f"  {self.personality.summary()}\n"
            f"  {self.signature.summary()}"
        )


# ─── Signature Generation ────────────────────────────────────────────────────

# The 12 root notes, mapped to numeric positions for deterministic selection
ROOT_NOTES = ["C", "C#", "D", "Eb", "E", "F", "F#", "G", "Ab", "A", "Bb", "B"]

# Mode mapping by alignment
ALIGNMENT_MODES = {
    Alignment.SAFE: ["major", "ionian", "lydian", "major pentatonic"],
    Alignment.BALANCED: ["dorian", "mixolydian", "major", "sus"],
    Alignment.CREATIVE: ["minor", "blues", "dorian", "aeolian", "phrygian"],
    Alignment.WILD: ["chromatic", "whole_tone", "phrygian", "locrian", "free atonal"],
}

# Chord quality by alignment
ALIGNMENT_CHORDS = {
    Alignment.SAFE: ["triad", "maj7", "maj9", "add9"],
    Alignment.BALANCED: ["sus4", "sus2", "dominant7", "maj7"],
    Alignment.CREATIVE: ["minor7", "minor9", "dominant7", "minor7b5"],
    Alignment.WILD: ["chromatic", "cluster", "minor-major7", "alt"],
}

# Dynamic levels in order
DYNAMICS_LEVELS = ["pp", "p", "mp", "mf", "f", "ff"]

# Time signatures by risk tolerance
TIME_SIGS_LOW_RISK = ["4/4", "3/4", "2/4"]
TIME_SIGS_MED_RISK = ["4/4", "6/8", "3/4", "5/4"]
TIME_SIGS_HIGH_RISK = ["5/4", "7/8", "6/8", "4/4", "11/8"]


def _seed_rng(seed: str) -> int:
    """Deterministic seed from a string."""
    return int(hashlib.md5(seed.encode()).hexdigest()[:8], 16)


def generate_signature_from_personality(
    personality: PersonalityWrap,
    seed: Optional[str] = None,
) -> MusicalSignature:
    """
    Generate a MusicalSignature from a PersonalityWrap.

    The mapping:
        alignment           → key, mode, chord quality
        risk_tolerance      → tempo, time signature
        creativity_score    → harmonic tension, dissonance, swing
        confidence_at_birth → intensity, dynamics
        verbosity           → articulation
        emotional_range     → additional color

    The signature is deterministic for the same personality + seed.
    """
    rng_seed = seed or f"{personality.model_name}:{personality.born_at}"
    h = _seed_rng(rng_seed)

    # --- Key and Mode (from alignment) ---
    modes = ALIGNMENT_MODES.get(personality.alignment, ALIGNMENT_MODES[Alignment.BALANCED])
    mode = modes[h % len(modes)]

    # Root note: hash personality traits to pick a note
    trait_sum = (
        personality.risk_tolerance
        + personality.creativity_score
        + personality.confidence_at_birth
        + personality.emotional_range
    )
    root_idx = int(trait_sum * 3 + (h % 12)) % 12
    root_note = ROOT_NOTES[root_idx]

    # Build key string
    if mode in ("major", "ionian", "lydian", "major pentatonic"):
        key = f"{root_note} major"
    elif mode in ("minor", "aeolian", "phrygian"):
        key = f"{root_note} minor"
    elif mode == "blues":
        key = f"{root_note} blues"
    elif mode == "chromatic":
        key = f"{root_note} chromatic"
    elif mode == "whole_tone":
        key = f"{root_note} whole-tone"
    else:
        key = f"{root_note} {mode}"

    # --- Tempo (from risk_tolerance) ---
    # cautious (0.0) = 50 BPM, bold (1.0) = 160 BPM
    tempo_bpm = int(50 + (personality.risk_tolerance * 110))
    # Add slight variation from hash
    tempo_bpm += (h >> 4) % 7 - 3  # ±3 BPM
    tempo_bpm = max(40, min(180, tempo_bpm))

    # --- Time Signature (from risk_tolerance) ---
    if personality.risk_tolerance < 0.33:
        time_sigs = TIME_SIGS_LOW_RISK
    elif personality.risk_tolerance < 0.67:
        time_sigs = TIME_SIGS_MED_RISK
    else:
        time_sigs = TIME_SIGS_HIGH_RISK
    time_signature = time_sigs[(h >> 8) % len(time_sigs)]

    # --- Harmonic Tension & Dissonance (from creativity_score) ---
    # Low creativity = resolved/consonant, High = tense/dissonant
    harmonic_tension = 0.1 + (personality.creativity_score * 0.8)
    dissonance = personality.creativity_score * 0.7

    # --- Chord Quality (from alignment) ---
    chords = ALIGNMENT_CHORDS.get(personality.alignment, ALIGNMENT_CHORDS[Alignment.BALANCED])
    chord_quality = chords[(h >> 12) % len(chords)]

    # --- Swing (from creativity + emotional_range) ---
    swing = (personality.creativity_score * 0.5 + personality.emotional_range * 0.3)
    swing = max(0.0, min(1.0, swing))

    # --- Intensity & Dynamics (from confidence_at_birth) ---
    intensity = personality.confidence_at_birth
    dyn_idx = int(personality.confidence_at_birth * (len(DYNAMICS_LEVELS) - 1))
    dynamics = DYNAMICS_LEVELS[max(0, min(len(DYNAMICS_LEVELS) - 1, dyn_idx))]

    # --- Articulation (from verbosity) ---
    # Terse = staccato, expansive = legato
    if personality.verbosity < 0.33:
        articulation = "staccato"
    elif personality.verbosity < 0.67:
        articulation = "mixed"
    else:
        articulation = "legato"

    # Add "blue" articulation for high creativity
    if personality.creativity_score > 0.7 and personality.alignment == Alignment.CREATIVE:
        articulation = "blue"

    return MusicalSignature(
        key=key,
        mode=mode,
        root_note=root_note,
        tempo_bpm=tempo_bpm,
        time_signature=time_signature,
        swing=round(swing, 3),
        harmonic_tension=round(harmonic_tension, 3),
        dissonance=round(dissonance, 3),
        chord_quality=chord_quality,
        intensity=round(intensity, 3),
        dynamics=dynamics,
        articulation=articulation,
        born_from=f"personality:{personality.model_name or 'unknown'}",
    )


# ─── Tile Chain (Session-level) ──────────────────────────────────────────────

@dataclass
class TileChain:
    """
    A chain of LivingTiles representing a session's musical/personality journey.
    The chain can be queried by the sonic shape engine for real-time generation.
    """
    session_id: str
    tiles: list[LivingTile] = field(default_factory=list)

    def add_tile(self, tile: LivingTile) -> None:
        """Add a tile to the chain."""
        self.tiles.append(tile)

    @property
    def signatures(self) -> list[MusicalSignature]:
        """Extract all musical signatures in order."""
        return [t.signature for t in self.tiles]

    @property
    def personalities(self) -> list[PersonalityWrap]:
        """Extract all personality wraps in order."""
        return [t.personality for t in self.tiles]

    @property
    def tempo_arc(self) -> list[int]:
        """The tempo journey across the session."""
        return [t.signature.tempo_bpm for t in self.tiles]

    @property
    def tension_arc(self) -> list[float]:
        """The harmonic tension journey across the session."""
        return [t.signature.harmonic_tension for t in self.tiles]

    @property
    def intensity_arc(self) -> list[float]:
        """The intensity journey across the session."""
        return [t.signature.intensity for t in self.tiles]

    @property
    def dominant_alignment(self) -> Alignment:
        """The most common alignment across all tiles."""
        if not self.tiles:
            return Alignment.BALANCED
        from collections import Counter
        counts = Counter(t.personality.alignment for t in self.tiles)
        return counts.most_common(1)[0][0]

    def to_dict(self) -> dict:
        """Full serialization."""
        return {
            "session_id": self.session_id,
            "tiles": [t.to_dict() for t in self.tiles],
            "tempo_arc": self.tempo_arc,
            "tension_arc": self.tension_arc,
            "intensity_arc": self.intensity_arc,
            "dominant_alignment": self.dominant_alignment.value,
        }

    def summary(self) -> str:
        """Human-readable chain summary."""
        lines = [
            f"TileChain [{self.session_id[:8]}] — {len(self.tiles)} tiles",
            f"Dominant alignment: {self.dominant_alignment.value}",
            f"Tempo arc: {' → '.join(str(t) for t in self.tempo_arc)}",
            f"Tension arc: {' → '.join(f'{t:.2f}' for t in self.tension_arc)}",
            f"Intensity arc: {' → '.join(f'{i:.2f}' for i in self.intensity_arc)}",
        ]
        return "\n".join(lines)
